apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-core-services-api
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: "1000m"
              memory: "4Gi"
          env:
            - name: ENV_NAME
              value: "production"
            - name: NODE_ENV
              value: "production"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/bedrock_production"
            - name: ADMIN_EMAIL
              value: "admin@bedrock.foundation"
            - name: ADMIN_PASSWORD
              value: "development.now"
            - name: APP_DOMAIN
              value: "bedrock.foundation"
            - name: APP_URL
              value: "https://bedrock.foundation"
            - name: POSTMARK_FROM
              value: "no-reply@bedrock.foundation"
            - name: UPLOADS_STORE
              value: "gcs"
            - name: UPLOADS_GCS_BUCKET
              value: "bedrock-production-uploads"
            - name: LOG_LEVEL
              value: "debug"
            # The `bedrock cloud` command in the CLI will help with
            # the creation and storing of secrets for production.
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_SECRET
            - name: POSTMARK_APIKEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTMARK_APIKEY
          ports:
            - name: http-server
              containerPort: 2300
          volumeMounts:
            - name: cache
              mountPath: /service/data
      volumes:
        - name: cache
          emptyDir: {}
