version: "3.7"

services:
  api:
    environment:
      - MONGO_URI=mongodb://mongo/bedrock_dev
    build:
      context: ./services/api
      dockerfile: Dockerfile
    volumes:
      - ./services/api/src:/service/src
      - ./services/api/emails:/service/emails
      - ./services/api/fixtures:/service/fixtures
      - ./services/api/scripts:/service/scripts
      - ./services/api/.env:/service/.env
      - ./services/api/openapi:/service/openapi
    ports:
      - "2300:2300"
    links:
      - mongo
    depends_on:
      - mongo

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./services/web/src:/service/src
    ports:
      - "2200:2200"
      - "34001:34001"
    depends_on:
      - api

  mongo:
    image: mongo:4.4.4
    command: --serviceExecutor adaptive
    logging:
      driver: none
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
