apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - image: gcr.io/bedrock-foundation/bedrock-services-web
          imagePullPolicy: Always
          name: main
          env:
            - name: NODE_ENV
              value: "staging"
            - name: DOMAIN
              value: bedrock.foundation
            - name: API_URL
              value: "https://api.bedrock.foundation"
          ports:
            - name: http-server
              containerPort: 2200
