name: Run Tests
on:
  [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working_directory: ./services/api
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
      working-directory: ${{ env.working_directory }}
    - run: yarn test --silent
      working-directory: ${{ env.working_directory }}
