apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 2300
      protocol: TCP
  selector:
    app: api
  loadBalancerIP: 34.74.255.5
